# .github/workflows/load-test.yml
name: Load Test with JMeter

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter
          jmeter --version

      - name: Install Node.js dependencies
        run: npm ci

      - name: Start the server in background
        run: |
          npm start &
          sleep 5

      - name: Run JMeter Load Test
        run: |
          mkdir -p reports
          jmeter -n -t load-test.jmx -l reports/results.jtl -e -o reports/html

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: reports/html
